### ISSUE TITLE
Support Laravel 10

### ISSUE THREAD

**Issue by midomario** [devinweb/laravel-youcan-pay#6]
Bonjour, je veux utiliser ce package avec la version 10 de Laravel, mais ça donne une erreur quand j'essaie de l'installer : 

**Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires devinweb/laravel-youcan-pay dev-feature/add_support_laravel_9 -> satisfiable by devinweb/laravel-youcan-pay[dev-feature/add_support_laravel_9].
    - devinweb/laravel-youcan-pay dev-feature/add_support_laravel_9 requires illuminate/support ^7.0|^8.0|^9.0 -> found illuminate/support[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.9] but these were not loaded, likely because it conflicts with another require.**

**Comment by darbaoui** [comment]
Thanks @inmass you can now upgrade to the latest version 0.4.3 that support laravel 10.x

**Comment by inmass** [comment]
Happy to help!
